### ISSUE TITLE
incorrect "invalid repo" error - collaboration section

### ISSUE THREAD

**Issue by no-stack-dub-sack** [FCC-Alumni/alumni-network#215]
@gwenf I see the error you were talking about before. Sometimes, when you add a project that you know if public and valid, you get a message that its invalid anyway, then when you retry it, it works. Sometimes on the 3rd try. 

When I began investigating, I found that the last `catch` is catching this error, and it seems to have to do with the `for...of` statement when we are trying to iterate through the list of contributors pulled from the GitHub API. However, it's a very unpredictable error, and I think it has to do with the API, when I went to try to debug a bit more, now I can't reproduce.

**Comment by gwenf** [comment]
Yes, it's hard to reproduce for me as well. It only happens sometimes. I wonder if we could give the user a messaged saying something unexpected happened and to try it again if it fails for no reason.

**Comment by smiller171** [comment]
@no-stack-dub-sack Could you link me to where in the code this is handled? I suspect there may be another concurrency bug.

**Comment by no-stack-dub-sack** [comment]
@gwenf I did try to add a couple of lines for that in the changes I just pushed - if the error caught in the `catch()` hook contains the error that I was getting when that happens, I added a specific error message for that just saying try again. 

@smiller171 the error is happening [here](https://github.com/FCC-Alumni/alumni-network/blob/master/client/src/components/dashboard/Profile/Preferences/common/RepoContainer.js#L259), but only sometimes. there was something about `Symbol[iterator]` related to `for...of` basically that `contributors` wasn't iterateable. So my guess was that the API didn't return to object of users as it was supposed to. So I added a specific conditional for that [here](https://github.com/FCC-Alumni/alumni-network/blob/master/client/src/components/dashboard/Profile/Preferences/common/RepoContainer.js#L308) to catch that error and return a specific error message.

**Comment by no-stack-dub-sack** [comment]
Closing this for now... the root of the problem is not fixed, and I think it may be out of our control. Unless it is some issue with the code I'm not seeing as @smiller171 suggests, however, the new error message I included as @gwenf suggested is working, so for now, lowish priority...

**Comment by smiller171** [comment]
@no-stack-dub-sack rather than closing issues like this, would managing priorities with something like [zenhub](https://www.zenhub.com/) be a better solution?

**Comment by no-stack-dub-sack** [comment]
@smiller171 maybe, but I'm concerned about over complicating things for the size and scope of the project. This seems to be a solved issue to me for the time being, I'm fairly certain it's not the code and that it's something weird with GitHub's API (but not positive, but the difficulty I've had in reproducing this lends to that theory). If the issue worsens, or pops up again, I'd gladly reopen.

Even if it was reopened, our issues are few enough where tracking priorities seems manageable for the time being.

**Comment by smiller171** [comment]
@no-stack-dub-sack ok. I tend to suspect a race condition because of how difficult it is to debug, but I haven't looked at it myself. I was offering it be kept open because you stated that it was "low priority" not solved or wontfix
